import { useState, useRef, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import ChatPanel, { ChatMessage } from "@/components/ChatPanel";
import PreviewPanel from "@/components/PreviewPanel";
import CodePanel, { CodeFile } from "@/components/CodePanel";
import DatabasePanel from "@/components/DatabasePanel";
import QuestionsDialog, { AIQuestion } from "@/components/QuestionsDialog";
import { streamGenerateWebsite, ThoughtBlock, DatabaseOperation } from "@/lib/aiService";
import { createTable, insertRow } from "@/lib/databaseService";
import { Code2, Eye, PanelRightOpen, Download, ArrowRight, Database } from "lucide-react";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";

const Index = () => {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isThinking, setIsThinking] = useState(false);
  const [previewHtml, setPreviewHtml] = useState("");
  const [codeFiles, setCodeFiles] = useState<CodeFile[]>([]);
  const [rightPanel, setRightPanel] = useState<"preview" | "code" | "database">("preview");
  const [showRightPanel, setShowRightPanel] = useState(true);
  const assistantContentRef = useRef("");
  const [aiQuestions, setAiQuestions] = useState<AIQuestion[]>([]);
  const [showQuestions, setShowQuestions] = useState(false);
  const [pendingUserMessage, setPendingUserMessage] = useState("");
  const [projectLoaded, setProjectLoaded] = useState(false);

  // Thought block state
  const [activeThought, setActiveThought] = useState<ThoughtBlock | null>(null);
  const [activeCompletedStep, setActiveCompletedStep] = useState(-1);

  // Load project data
  useEffect(() => {
    if (!projectId) return;
    const load = async () => {
      const { data, error } = await supabase
        .from("projects")
        .select("*")
        .eq("id", projectId)
        .single();

      if (error || !data) {
        toast({ title: "خطأ", description: "المشروع غير موجود", variant: "destructive" });
        navigate("/");
        return;
      }

      if (data.chat_history && Array.isArray(data.chat_history)) {
        setMessages(
          (data.chat_history as any[]).map((m: any) => ({
            ...m,
            timestamp: new Date(m.timestamp),
          }))
        );
      }
      if (data.preview_html) setPreviewHtml(data.preview_html);
      if (data.code_files && Array.isArray(data.code_files)) {
        setCodeFiles(data.code_files as unknown as CodeFile[]);
      }
      setProjectLoaded(true);
    };
    load();
  }, [projectId]);

  // Auto-save project
  useEffect(() => {
    if (!projectId || !projectLoaded) return;
    const timeout = setTimeout(() => {
      supabase
        .from("projects")
        .update({
          preview_html: previewHtml || null,
          code_files: codeFiles as any,
          chat_history: messages.map((m) => ({
            ...m,
            timestamp: m.timestamp.toISOString(),
          })) as any,
          updated_at: new Date().toISOString(),
        })
        .eq("id", projectId)
        .then(({ error }) => {
          if (error) console.error("Auto-save error:", error);
        });
    }, 2000);
    return () => clearTimeout(timeout);
  }, [messages, previewHtml, codeFiles, projectId, projectLoaded]);

  const handleDownloadZip = async () => {
    if (codeFiles.length === 0 && !previewHtml) {
      toast({ title: "لا يوجد ملفات", description: "قم بإنشاء موقع أولاً", variant: "destructive" });
      return;
    }
    const zip = new JSZip();
    codeFiles.forEach((file) => zip.file(file.name, file.content));
    if (previewHtml) zip.file("index.html", previewHtml);
    zip.file("README.md", `# Generated by AI Site Forge\n\nCreated: ${new Date().toISOString()}`);
    const blob = await zip.generateAsync({ type: "blob" });
    saveAs(blob, "ai-site-forge-project.zip");
    toast({ title: "تم التحميل!", description: "تم تنزيل ملفات المشروع بنجاح" });
  };

  const handleSendMessage = async (content: string) => {
    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: "user",
      content,
      timestamp: new Date(),
    };
    setMessages((prev) => [...prev, userMsg]);
    setIsGenerating(true);
    setIsThinking(true);
    setShowRightPanel(true);
    assistantContentRef.current = "";

    // Reset thought state
    setActiveThought(null);
    setActiveCompletedStep(-1);

    const chatHistory = [...messages, userMsg].map((m) => ({
      role: m.role as "user" | "assistant",
      content: m.content,
    }));

    // Track the thought for attaching to the final message
    let capturedThought: ThoughtBlock | null = null;
    // Track the AI message id
    let aiMsgId: string | null = null;

    try {
      await streamGenerateWebsite(chatHistory, {
        onThinking: (thinking) => {
          setIsThinking(thinking);
          if (!thinking) {
            aiMsgId = (Date.now() + 1).toString();
            setMessages((prev) => [
              ...prev,
              { id: aiMsgId!, role: "assistant", content: "", timestamp: new Date() },
            ]);
          }
        },

        onThought: (thought) => {
          capturedThought = thought;
          setActiveThought(thought);
          setActiveCompletedStep(0);
        },

        onStepComplete: (stepIndex) => {
          setActiveCompletedStep(stepIndex);
        },

        onTextDelta: (delta) => {
          assistantContentRef.current += delta;
          const currentText = assistantContentRef.current;
          setMessages((prev) => {
            const last = prev[prev.length - 1];
            if (last?.role === "assistant") {
              return prev.map((m, i) =>
                i === prev.length - 1 ? { ...m, content: currentText } : m
              );
            }
            return [
              ...prev,
              {
                id: (Date.now() + 1).toString(),
                role: "assistant",
                content: currentText,
                timestamp: new Date(),
              },
            ];
          });
        },

        onComplete: (result) => {
          if (result.questions && result.questions.length > 0) {
            setAiQuestions(result.questions);
            setShowQuestions(true);
            setPendingUserMessage(content);
            setIsGenerating(false);
            setIsThinking(false);
            setActiveThought(null);
            return;
          }

          // Attach the captured thought to the last assistant message
          if (capturedThought) {
            setMessages((prev) => {
              const last = prev[prev.length - 1];
              if (last?.role === "assistant") {
                return prev.map((m, i) =>
                  i === prev.length - 1
                    ? { ...m, content: result.reply || m.content, thought: capturedThought! }
                    : m
                );
              }
              return prev;
            });
          } else if (result.reply) {
            setMessages((prev) => {
              const last = prev[prev.length - 1];
              if (last?.role === "assistant") {
                return prev.map((m, i) =>
                  i === prev.length - 1 ? { ...m, content: result.reply } : m
                );
              }
              return [
                ...prev,
                {
                  id: (Date.now() + 1).toString(),
                  role: "assistant",
                  content: result.reply,
                  timestamp: new Date(),
                },
              ];
            });
          }

          if (result.html) {
            setPreviewHtml(result.html);
            setRightPanel("preview");
          }
          if (result.files.length > 0) setCodeFiles(result.files);

          // Handle database operations from AI
          if (result.database && projectId) {
            handleDatabaseOps(result.database);
          }

          // Clear active thought
          setActiveThought(null);
          setActiveCompletedStep(-1);
          setIsGenerating(false);
          setIsThinking(false);
        },

        onError: (error) => {
          toast({ title: "Error", description: error, variant: "destructive" });
          setActiveThought(null);
          setIsGenerating(false);
          setIsThinking(false);
        },
      });
    } catch (e) {
      toast({
        title: "Connection Error",
        description: "Failed to connect to AI. Please try again.",
        variant: "destructive",
      });
      setActiveThought(null);
      setIsGenerating(false);
      setIsThinking(false);
    }
  };

  const handleQuestionsSubmit = (answers: Record<string, string>) => {
    setShowQuestions(false);
    const answersText = aiQuestions.map((q) => `${q.question}: ${answers[q.id]}`).join("\n");
    const fullMessage = `${pendingUserMessage}\n\nAnswers:\n${answersText}`;
    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: "user",
      content:
        "تم تحديد التفضيلات:\n" +
        aiQuestions.map((q) => "- " + q.question + " -> " + answers[q.id]).join("\n"),
      timestamp: new Date(),
    };
    setMessages((prev) => [...prev, userMsg]);
    handleSendMessage(fullMessage);
  };

  return (
    <div className="flex h-screen bg-background overflow-hidden">
      <div
        className={`flex flex-col border-r border-border transition-all duration-300 ${
          showRightPanel ? "w-[65%]" : "w-full"
        }`}
      >
        {/* Back button */}
        <div className="flex items-center gap-2 px-3 py-1.5 border-b border-border bg-card">
          <Button
            variant="ghost"
            size="sm"
            className="h-7 text-xs gap-1 text-muted-foreground"
            onClick={() => navigate("/")}
          >
            <ArrowRight className="w-3.5 h-3.5" />
            المشاريع
          </Button>
        </div>
        <ChatPanel
          messages={messages}
          onSendMessage={handleSendMessage}
          isGenerating={isGenerating}
          isThinking={isThinking}
          activeThought={activeThought}
          activeCompletedStep={activeCompletedStep}
        />
      </div>

      {showRightPanel && (
        <div className="flex-1 flex flex-col min-w-0 animate-fade-in">
          <div className="flex items-center justify-between px-3 py-2 bg-card border-b border-border">
            <div className="flex items-center gap-1">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setRightPanel("preview")}
                className={`h-7 text-xs gap-1.5 ${
                  rightPanel === "preview" ? "bg-secondary text-primary" : "text-muted-foreground"
                }`}
              >
                <Eye className="w-3.5 h-3.5" /> Preview
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setRightPanel("code")}
                className={`h-7 text-xs gap-1.5 ${
                  rightPanel === "code" ? "bg-secondary text-primary" : "text-muted-foreground"
                }`}
              >
                <Code2 className="w-3.5 h-3.5" /> Code
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setRightPanel("database")}
                className={`h-7 text-xs gap-1.5 ${
                  rightPanel === "database" ? "bg-secondary text-primary" : "text-muted-foreground"
                }`}
              >
                <Database className="w-3.5 h-3.5" /> Database
              </Button>
            </div>
            <div className="flex items-center gap-1">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleDownloadZip}
                disabled={codeFiles.length === 0 && !previewHtml}
                className="h-7 text-xs gap-1.5 text-muted-foreground"
              >
                <Download className="w-3.5 h-3.5" /> ZIP
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setShowRightPanel(false)}
                className="h-7 w-7 p-0 text-muted-foreground"
              >
                <PanelRightOpen className="w-3.5 h-3.5" />
              </Button>
            </div>
          </div>
          <div className="flex-1 min-h-0 relative">
            {rightPanel === "preview" ? (
              <PreviewPanel html={previewHtml} isGenerating={isGenerating} />
            ) : rightPanel === "code" ? (
              <CodePanel files={codeFiles} />
            ) : (
              projectId ? <DatabasePanel projectId={projectId} /> : null
            )}
          </div>
        </div>
      )}

      {!showRightPanel && (
        <button
          onClick={() => setShowRightPanel(true)}
          className="fixed right-4 top-4 z-50 p-2 rounded-lg bg-secondary border border-border text-muted-foreground hover:text-foreground transition-colors"
        >
          <PanelRightOpen className="w-4 h-4" />
        </button>
      )}

      <QuestionsDialog
        open={showQuestions}
        questions={aiQuestions}
        onSubmit={handleQuestionsSubmit}
        onClose={() => setShowQuestions(false)}
      />
    </div>
  );
};

export default Index;
